
package pl.edu.agh.soa.lab9;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DayCounterService", targetNamespace = "http://lab9.soa.agh.edu.pl/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface DayCounterService {


    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(partName = "return")
    public long countDays();

}
